### ISSUE TITLE
Entering nether crashes game

### ISSUE THREAD

**Issue by Hamsterrhino** [DysfunctionalDev/DysfunctionalWarfare#2]
[latest.log](https://github.com/DysfunctionalDev/DysfunctionalWarfare/files/11377933/latest.log)
On the line 8498 at 00:41:09 i was tabbing in and out of game to check logs work
On 8507 at 00:41:18 walked into nether portal
Seems something related to xaero.map mod that crashes game
Game tries to load something because CPU usage jumps up and down and memory usage slowly goes up.

**Comment by TheHexangle** [comment]
Could you reply with the crash report or log from that session.

**Comment by Hamsterrhino** [comment]
Well I posted log in first message I think?
And there is no crash log because it just stopped working

**Comment by TheHexangle** [comment]
Sorry didn't see it at first.

**Comment by TheHexangle** [comment]
You're correct about Xaero's World Map being the problem, my first thought was maybe you ran out of RAM but it says you have 16GB allocated to it this is more than twice the ram needed so that's no issue. If 16GB is the total amount of RAM in your system lower it to 8GB and try to enter the nether, if that doesn't work reboot your system and update your operating system and drivers. I believe this is a hardware/software issue due to the system usage you mentioned. If not I'll try an recreate the issue and see if I can find a fix if the issue persists.

**Comment by Hamsterrhino** [comment]
I have 64 gb of ram total so doubt that
One of things might be turning on peaceful and going into nether, building
stone box and turning on normal. Just one of things I did

**Comment by TheHexangle** [comment]
Found a fix, for now manually update both Xaero's World Map and Mini Map. It's an issue with the older release this will be patched and pushed to Curse Forge immediately.
